use_frameworks!

target 'Extra_Example' do
  pod 'Extra', :path => '../'
  
  pod 'SwiftGen', '~> 4.0.1'
  pod 'RxCocoa', '~> 3.0.1'

  target 'Extra_Tests' do
    inherit! :search_paths

#pod 'FBSnapshotTestCase'
  end
end
